# Generated by Django 5.1.4 on 2025-01-01 11:49

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='style_images/', verbose_name='缩略图')),
            ],
            options={
                'verbose_name': '风格',
                'verbose_name_plural': '风格',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='缩略图')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='image.category')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='software_images/', verbose_name='缩略图')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='image.model')),
            ],
            options={
                'verbose_name': '软件',
                'verbose_name_plural': '软件',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('cn_prompt', models.TextField(verbose_name='中文提示词')),
                ('author_generated', models.CharField(max_length=32, verbose_name='作者')),
                ('images', models.JSONField(default=list, verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='image.category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='image.software')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='image.style')),
            ],
            options={
                'verbose_name': '条目',
                'verbose_name_plural': '条目',
            },
        ),
    ]
