# Generated by Django 5.1.4 on 2025-01-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_author_remove_item_author_generated_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='image.category', verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='software',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='software', to='image.model'),
        ),
    ]
