# Generated by Django 5.1.4 on 2025-01-03 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_alter_image_options_item_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='copy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('BR', '巴西葡语')], default='BR', max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='image.author', verbose_name='生成人员'),
        ),
    ]
