# Generated by Django 5.1.4 on 2025-01-07 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_item_copy_count_item_language_item_likes_item_views_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('BR', '巴西葡语'), ('ES', '西语'), ('MJ', '美加')], default='BR', max_length=32),
        ),
    ]
