# Generated by Django 5.1.4 on 2025-01-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_item_reviewed_by_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
