# Generated by Django 5.1.4 on 2025-01-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_item_deleted_at_item_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('BR', '巴西葡语'), ('ES', '西语'), ('MJ', '美加')], default='BR', max_length=32, verbose_name='语系'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '已拒绝')], default='pending', max_length=32, verbose_name='审核状态'),
        ),
    ]
