# Generated by Django 5.1.4 on 2025-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_image_filename_alter_item_language_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核日期'),
        ),
    ]
