# Generated by Django 5.1.4 on 2025-02-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_software_cons_software_pros_software_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='拒绝原因'),
        ),
    ]
