# Generated by Django 5.1.4 on 2025-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_item_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='input_type',
            field=models.CharField(choices=[('text', '提示词'), ('image', '图片+提示词')], default='image', max_length=10, verbose_name='类型'),
        ),
    ]
